/**
 * Created by zhuzhiyang on 2016/12/29
 */

// GLOBAL
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const TOGGLE_SELECTSTATUS = 'TOGGLE_SELECTSTATUS'
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH'
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const SET_CURRENT_HEADER_INFO = 'SET_CURRENT_HEADER_INFO'
export const GET_TOKEN = 'GET_TOKEN'
export const SET_TOKEN = 'SET_TOKEN'
// timeline for all
export const GET_ALL_TIMELINE = 'GET_ALL_TIMELINE'
export const GET_PART_TIMELINE = 'GET_PART_TIMELINE'

// USER
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const SET_USER = 'SET_USER'
export const DROP_USER = 'DROP_USER'
export const TOGGLE_USER = 'TOGGLE_USER'

// POST
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const RE_RECEIVE_POSTS = 'RE_RECEIVE_POSTS'
export const SET_POSTS_INFO = 'SET_POSTS_INFO'
export const RESET_POSTS_INFO = 'RESET_POSTS_INFO'
export const TOGGLE_POST = 'TOGGLE_POST'

// TAG
export const RECEIVE_TAG = 'RECEIVE_TAG'
export const CREATE_TAG = 'CREATE_TAG'
export const MODIFY_TAG = 'MODIFY_TAG'

// MESSAGE
export const RECEIVE_COUNT = 'RECEIVE_COUNT'
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
export const MARK_MESSAGE = 'MARK_MESSAGE'
export const MARK_ALL_MESSAGE = 'MARK_ALL_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const TOGGLE_MESSAGE_COMMENT_STATUS = 'TOGGLE_MESSAGE_COMMENT_STATUS'
